
context("Test to make sure lat checks and long checks are ok")

test_that("lat and long checks work correctly", {
    expect_false(test_lat(-1900))
    expect_true(test_lat(-89))
    expect_false(test_long(-1800))
    expect_true(test_long(-89))
})


context("Testing the aggregate function")

test_that("aggregates work correctly", {

dat  <- structure(list(departement = structure(c(5L, 47L, 18L, 9L, 14L, 
9L), .Label = c("AIN", "AISNE", "ALLIER", "ARDENNES", "AUBE", 
"BAS-RHIN", "C\xd4TE-D'OR", "CALVADOS", "CHARENTE", "CHER", "CREUSE", 
"DEUX-S\xc8VRES", "DORDOGNE", "EURE", "EURE-ET-LOIR", "GIRONDE", 
"HAUT-RHIN", "HAUTE-MARNE", "HAUTE-SA\xd4NE", "HAUTE-VIENNE", 
"INDRE", "INDRE-ET-LOIRE", "JURA", "LOIR-ET-CHER", "LOIRET", 
"MAINE-ET-LOIRE", "MANCHE", "MARNE", "MAYENNE", "MEURTHE-ET-MOSELLE", 
"MEUSE", "MOSELLE", "NI\xc8VRE", "NORD", "OISE", "ORNE", "PAS-DE-CALAIS", 
"PUY-DE-D\xd4ME", "PYR\xc9N\xc9ES-ATLANTIQUES", "RH\xd4NE", "SA\xd4NE-ET-LOIRE", 
"SARTHE", "SAVOIE", "SEINE-ET-MARNE", "SEINE-MARITIME", "SOMME", 
"VIENNE", "VOSGES", "YONNE"), class = "factor"), commune = structure(c(992L, 
522L, 810L, 740L, 116L, 756L), .Label = c("\xc9pen\xe8de", "\xc9perrais", 
"\xc9poisses", "\xc9riseul", "\xc9tagnac", "\xc9talleville", 
"\xc9tr\xe9aupont", "\xc9treillers", "\xc9troeungt", "abilly", 
"Abzac", "ABZAC", "ACY", "Adriers", "ADRIERS", "AFFLEVILLE", 
"Agincourt", "Ailly-le-Haut-Clocher", "Aisey-et-Richecourt", 
"Aixe-sur-Vienne", "Aizy Jouy", "Alincthun", "ALLICHAMPS", "ALLOUE", 
"Allouville-Bellefosse", "Ambernac", "Andilly-en-Bassigny", "Andryes", 
"Angely", "ANOST", "Anrosey", "Ansac-sur-Vienne", "ANSAC-SUR-VIENNE", 
"ANSAUVILLERS", "Anv\xe9ville", "Archigny", "ARGILLIERES", "ARGY", 
"ARMES", "Arnac-la-Poste", "Arrest", "Artannes-sur-Indre", "Asni\xe8res-sur-Blour", 
"ASNIERES-SUR-BLOUR", "ASPACH", "Attin", "Atton", "Auberville-la-Renault", 
"AUCHY-LEZ-ORCHIES", "Audincthun", "AUDINGHEN", "Audruicq", "AULT", 
"Aunay-sur-Odon", "Authe", "Authieule", "Autigny-la-Tour", "Autrey", 
"AUTREY", "AUXAIS", "Availles-Limouzine", "AVAILLES-LIMOUZINE", 
"Avelin", "Avermes", "Avesnelles", "AVESNES-LE-SEC", "Avrecourt", 
"AVROULT", "Awoingt", "AYDOILLES", "AZAT-LE-RIS", "Azay-le-Ferron", 
"AZAY-LE-FERRON", "AZAY-LE-RIDEAU", "Azoudange", "AZY-LE-VIF", 
"B\xe9court", "B\xe9nouville", "B\xe9thines", "Bacourt", "Bacqueville-en-Caux", 
"Bagneux", "Bailleul", "BAINVILLE-SUR-MADON", "BALLAY", "Balledent", 
"BALLEDENT", "Baons-le-Comte", "BARBAS", "Basse-sur-le-Rupt", 
"Bauzemont", "BAVINCOURT", "Bay-sur Aube", "BAZELAT", "BEAULIEU", 
"Beauquesne", "Beaurepaire", "Beaurepaire-en-Bresse", "Beauvilliers", 
"BEGROLLES-EN-MAUGES", "Bellac", "Belrupt", "Belval-sous-Ch\xe2tillon", 
"BERCK", "BEREZIAT", "Berneuil", "Bernouville", "BERTHEN", "BERUGES", 
"BESSINES-SUR-GARTEMPE", "BETHINES", "Bettoncourt-le-Haut", "Beurizot", 
"Beurville", "Beux", "Beuzeville", "Beuzeville-la-Grenier", "Bezaumont", 
"Biarre", "Billy-sous-les-C\xf4tes", "BISLEE", "Bissey-sous-Cruchaud", 
"Biville-la-Baignarde", "BIZIAT", "BLANCHEFOSSE-ET-BAY", "Blanzac", 
"BLANZAC", "BLARINGHEM", "Blessonville", "Blicourt", "Blond", 
"Bolbec", "Bolleville", "Bonneuil", "Bonny-sur-Loire", "Bossancourt", 
"BOUESSE", "Bougey", "BOULAY-MOSELLE", "Bourbonne-les-Bains", 
"Bouresse", "BOURESSE", "Bourg-Archambault", "BOURG-ARCHAMBAULT", 
"Boz", "Br\xe9aut\xe9", "Br\xe9m\xe9nil", "Br\xe9moncourt", "Braux", 
"BREVES", "Briantes", "Bricquebec", "BRICQUEBEC", "Brigueil-le-Chantre", 
"BRIGUEIL-LE-CHANTRE", "Brigueuil", "BRIGUEUIL", "Brillac", "BRILLAC", 
"BRIXEY-AUX-CHANOINES", "Brulange", "Brunehamel", "Brutelles", 
"Bucamps", "Buffign\xe9court", "Buhl-Lorraine", "BURTHECOURT-AUX-CHENES", 
"Bussi\xe8re-Poitevine", "BUSSIERE-BOFFY", "BUSSIERE-POITEVINE", 
"Buxi\xe8res-d'Aillac", "BUXIERES-LES-MINES", "C\xe9lon", "CABANAC-ET-VILLAGRAINS", 
"Cambremer", "Cannectancourt", "Canville-les-Deux-\xc9glises", 
"Carignan", "CARQUEBUT", "CATIGNY", "Catillon-sur-Sambre", "Caunay", 
"Cavron-Saint-Martin", "CERE-LA-RONDE", "CERENCES", "CERISY-LA-SALLE", 
"Ch\xe2teau-Garnier", "ch\xe2teau-salins", "Ch\xe2teauponsac", 
"Ch\xe2tenay-Vaudin", "Ch\xe2tenois", "Ch\xe9zeaux", "Ch\xe9zy-en-Orxois", 
"Chablis", "CHABRIS", "Chaillac", "CHAILLAC", "CHAILLAC-SUR-VIENNE", 
"Chailly-sur-Arman\xe7on", "CHALAIS", "Chalindrey", "CHALLERANGE", 
"CHAMARANDES-CHOIGNES", "Chamboret", "Chambrey", "CHAMPAGNE-SAINT-HILAIRE", 
"Champigny-sous-Varennes", "CHAMPS", "CHAMPSEVRAINE", "Chantelle", 
"Chaouilley", "Charbuy", "CHARLEVILLE-SOUS-BOIS", "Charmes-la-Grande", 
"CHARMES-LA-GRANDE", "charroux", "Chassey-l\xe8s-Montbozon", 
"CHATEAU-CHINON(CAMPAGNE)", "CHATEAU-GARNIER", "CHATEAUPONSAC", 
"Chaudenay", "CHAUMONT-LA-VILLE", "Chaumont-Porcien", "Chauvigny", 
"CHAVEYRIAT", "Chazelet", "CHAZELLES", "CHEHERY", "Chemery", 
"CHEMERY", "Chemin-d'Aisey", "CHENIERS", "Cherbourg", "CHERVES-CHATELARS", 
"Chevannes", "CHEVERNY", "Chevillon", "CHEVROCHES", "Chicourt", 
"CHIRAC", "Cieux", "Ciron", "Civrieux", "Cizay-la-Madeleine", 
"Cl\xe9rey-sur-Br\xe9non", "Cl\xe9zentaine", "CLAIRFONTAINE", 
"Clamecy", "CLAMECY", "CLERE-DU-BOIS", "Clinchamps-sur-Orne", 
"CLION", "Coiffy-le-Haut", "COINGT", "Colombey-les-Belles", "COLOMBEY-LES-DEUX-EGLISES", 
"COLONDANNES", "Combres-sous-les-C\xf4tes", "COMBREUX", "Cond\xe9-Northen", 
"CONDE-NORTHEN", "CONFOLENS", "Confran\xe7on", "CONGE-SUR-ORNE", 
"Conthil", "Corpoyer-la-Chapelle", "COSSAYE", "Cossesseville", 
"Coulandon", "COULLEMONT", "Coulmier-le-Sec", "Coulonges", "COULONGES", 
"Coulonges-sur-Sarthe", "Coupelle-Vieille", "COURCELLES-LES-SEMUR", 
"COURGEON", "COURTESOULT-ET-GATEY", "Coussay-les-Bois", "COUVERTPUIS", 
"Coyviller", "Cr\xe9quy", "CRECY-SUR-SERRE", "CREQUY", "CRIEL-SUR-MER", 
"Crion", "CROISY", "CROMAC", "CRUGNY", "Crupilly", "CULAN", "Cussay", 
"Cuves", "D\xe9deling", "Dammartin-sur-Meuse", "Darnac", "DARNAC", 
"Delettes", "DELETTES", "Dercy", "Desvres", "DIEVAL", "Dinsac", 
"DOMBROT-SUR-VAIR", "Domecy-sur-Cure", "Domgermain", "Domjulien", 
"DOMMARTIN-DAMPIERRE", "Dompierre-les-\xc9glises", "Dompierre-sur-Authie", 
"Domptail", "Donzy", "Doudeauville", "Douvrend", "DOVILLE", "Dracy", 
"Dracy-Saint-Loup", "Drambon", "Droisy", "Droux", "Dunet", "ECUEILLE", 
"ECUIRES", "ECULLEVILLE", "Emberm\xe9nil", "Empur\xe9", "Englesqueville-en-Auge", 
"Envronville", "EPAIGNES", "epinac", "EPINAL", "Escles", "Escombres-et-le-Chesnois", 
"Esley", "Esse", "ESSE", "Euilly-et-Lombut", "EXIDEUIL", "Eywiller", 
"FAULQUEMONT", "Faulx", "FAULX", "Faveraye-Machelles", "FAYE-L'ABBESSE", 
"FAYL-BILLOT", "FEYTIAT", "Fill\xe9", "FLAGEY", "Fleury-la-For\xeat", 
"FLIGNY", "Flor\xe9mont", "Fluqui\xe8res", "FOAMEIX-ORNEL", "Fontaine-au-Bois", 
"Fontaine-l\xe8s-Vervins", "Fontaine-le-Dun", "FONTAINE-LES-VERVINS", 
"Fontaines", "Fontangy", "FONTENELLE", "formigny", "Fossieux", 
"Foucart", "Foulcrey", "Fouligny", "Fourcigny", "FOURS", "Fr\xe9monville", 
"Fr\xe9vent", "Fr\xf4lois", "Fraignot-et-Vesvrotte", "Framicourt", 
"Fraquelfing", "Freb\xe9court", "Frenelle-la-Grande", "Freneuse-sur-Risle", 
"Fresnes-en-Saulnois", "Fresnes-en-Tardenois", "FRESNOY-FOLNY", 
"Fromy", "FRONTENARD", "G\xe9lucourt", "GAJOUBERT", "GARGILESSE-DAMPIERRE", 
"Gemmelaincourt", "GEMONVILLE", "Genouillac", "Gerb\xe9viller", 
"Gergny", "GERMINY", "Gevrolles", "Ghyvelde", "GIEVILLE", "ginai", 
"Giraumont", "Givron", "Gizay", "Glanges", "GLOS-LA-FERRIERE", 
"GODERVILLE", "GOLLEVILLE", "GONCOURT", "Gonneville", "GONNEVILLE-EN-AUGE", 
"Gouberville", "Gouex", "GOUEX", "Gournay", "GOURNAY-EN-BRAY", 
"Goviller", "Grand", "Grand Rullecourt", "GRAND-CAMP", "Grandcourt", 
"Greuville", "GREZ", "Grez-en-Bou\xe8re", "Grivy-Loisy", "GROSSOUVRE", 
"Grosville", "Gu\xe9bling", "GUILLON", "Guilly", "Guincourt", 
"GUIPY", "H\xe9nam\xe9nil", "Haboudange", "Haillainville", "Hambye", 
"Hammeville", "HANNACHES", "HARGICOURT", "Hary", "HAUT-LIEU", 
"HAUTE-AMANCE", "Haute-Kontz", "HAUTEFONTAINE", "Hauteroche", 
"HAUTTEVILLE-BOCAGE", "HAZEBROUCK", "Hennezel", "Hermanville", 
"Heugleville-sur-Scie", "HEUGNES", "Honnechy", "Honskirch", "HORNAING", 
"HORNOY-LE-BOURG", "Hou\xe9ville", "Houdelaincourt", "HOUECOURT", 
"Hugleville-en-Caux", "Hurecourt", "Ibigny", "ILLKIRCH-GRAFFENSTADEN", 
"Imbleville", "Incourt", "INCOURT", "Insming", "Is-en-Bassigny", 
"ISENAY", "Jaulges", "Jeantes", "JEANTES", "JEU-LES-BOIS", "Jouac", 
"Jouhet", "JOUHET", "JOURNET", "JOUSSE", "JUGY", "JUVIGNIES", 
"KIRRWILLER-BOSSELSHAUSEN", "L'\xc9tang-Bertrand", "L'Isle-Jourdain", 
"La Bazeuge", "LA BERTHENOUX", "LA BESACE", "La Blouti\xe8re", 
"La Celle-Gu\xe9nand", "LA CELLE-SUR-LOIRE", "La Cerlangue", 
"La Chapelle-Bertrand", "La Chapelle-Montreuil", "LA CHAPELLE-MONTREUIL", 
"La Chapelle-Th\xe8cle", "LA COLOMBE", "LA COMTE", "LA COURBE", 
"La Croix-sur-Gartempe", "LA CROIX-SUR-GARTEMPE", "LA FEREE", 
"LA FERMETE", "La Ferri\xe8re-en-Parthenay", "La Fert\xe9-Loupi\xe8re", 
"La Gaillarde", "La Godefroy", "La Haye-du-Puits", "La Loge", 
"LA MANCELIERE", "La Mothe-Saint-H\xe9ray", "La P\xe9rouille", 
"LA PERCHE", "LA PERNELLE", "LA PUYE", "La Roche-Chalais", "La Roche-en-Brenil", 
"La Roche-Posay", "LA ROCHE-VANNEAU", "La Souterraine", "LA SUZE-SUR-SARTHE", 
"La Trimouille", "LA TRIMOUILLE", "La Vineuse", "Lagarde", "Laitre-sous-Amance", 
"Lamarche", "Landange", "LANDOUZY-LA-VILLE", "LANGRUNE-SUR-MER", 
"LANTAGES", "LATHUS-SAINT-REMY", "Launstroff", "Lavall\xe9e", 
"LAVAUSSEAU", "Le B\xe9ny-Bocage", "Le Blanc", "LE BLANC", "Le Bourg-d'Hem", 
"LE CATEAU-CAMBRESIS", "LE CHATELET", "LE DORAT", "Le Doulieu", 
"Le F\xeate", "LE LOUROUX", "LE MAY-SUR-EVRE", "LE MENIL-GUYON", 
"Le Mesnil-Eudes", "Le Mesnil-Raoult", "LE MESNIL-ROGUES", "Le Mesnilbus", 
"Le Nouvion-en-Thi\xe9rache", "LE PECHEREAU", "LE PIN", "LE PLESSIER-SUR-BULLES", 
"Le Reculey", "LE SOUICH", "Le Torpt", "Le Val-Saint-P\xe8re", 
"Le Vigeant", "LE VIGEANT", "Le Vr\xe9tot", "Leignes-sur-Fontaine", 
"Leintrey", "Lengronne", "LENT", "Les Forges", "Les Grands Ch\xe9zeaux", 
"LES LOGES", "Les Thons", "LES TROIS-PIERRES", "LESMENILS", "Lessac", 
"Lesterps", "LEULINGHEM", "Levoncourt", "Levroux", "Liernais", 
"LIESVILLE-SUR-DOUVE", "LIFFOL-LE-GRAND", "Liglet", "LIGLET", 
"Lignac", "LIGNAC", "LIGNEREUIL", "LIGNIERES-CHATELAIN", "Lignol-le-Ch\xe2teau", 
"LIMANTON", "LIMOGES", "Limonest", "Linselles", "Lironville", 
"LIVERDUN", "Lochwiller", "Loison", "Long", "Longeville-en-Barrois", 
"Longeville-sur-la-Laines", "Longpr\xe9-les-Corps-Saints", "Longvillers", 
"LORMES", "Lottinghen", "Louvencourt", "Louvi\xe8res", "Lu\xe7ay-le-M\xe2le", 
"LUANT", "LUCE-SOUS-BALLON", "Luchapt", "Lussac", "LUSSAC", "Lussac-les-\xc9glises", 
"Lussac-les-Ch\xe2teaux", "LUSSAC-LES-EGLISES", "Luttange", "LUZERET", 
"LYE", "M\xe9nil-en-Xaintois", "M\xe9nil-sur-Belvitte", "M\xe9obecq", 
"M\xe9ry-la-Bataille", "M\xe9zi\xe8res-sur-Issoire", "Magnac-Laval", 
"MAGNAC-LAVAL", "Magneville", "Magny", "Magny-le-Freule", "Mailhac-sur-Benaize", 
"MAILHAC-SUR-BENAIZE", "MAILLET", "Mailly-sur-Seille", "MAISON-MAUGIS", 
"MAISONCELLE-TUILERIE", "Maixe", "Maizi\xe8res", "Malaincourt-sur-Meuse", 
"MALICORNAY", "Man\xe9houville", "MANDRES-EN-BARROIS", "Manerbe", 
"Manglieu", "MANNEVILLE-LA-PIPARD", "Manoncourt-en-Vermois", 
"Manoncourt-sur-Seille", "MARAINVILLER", "MARANGE-ZONDRANGE", 
"Marault", "Marchais-en-Brie", "MARCHESEUIL", "Marcilly-en-Bassigny", 
"MARCILLY-EN-BASSIGNY", "MARIGNY", "MARIGNY-BRIZAY", "Marigny-l'\xc9glise", 
"Marnay", "Martigny", "Martincourt", "MARTIZAY", "Marville", 
"Marzy", "MASSIGNAC", "Mattexey", "Maupr\xe9voir", "MAUPREVOIR", 
"MAUX", "Mavilly-Mandelot", "Mazerolles", "Mazingarbe", "Meillant", 
"MELLEROY", "MENETOU-RATEL", "MENEVILLERS", "MERLAUT", "Mers-sur-Indre", 
"MERS-SUR-INDRE", "Mesnil-Domqueur", "Metz-Robert", "Meuvy", 
"Mietesheim", "MILLERY", "MIRECOURT", "MISSE", "MONCEAU-SAINT-WAAST", 
"MONCHIET", "Mons-Boubert", "MONS-EN-LAONNOIS", "Mont-Bonvillers", 
"MONT-ET-MARRE", "MONT-LES-LAMARCHE", "Montauban-de-Picardie", 
"MONTBOUY", "MONTCAVREL", "MONTCHEVRIER", "Montheries", "Montiers-sur-Saulx", 
"MONTIERS-SUR-SAULX", "MONTIGNY-EN-CAMBRESIS", "Montigny-l\xe8s-Vaucouleurs", 
"Montigny-Montfort", "Montlou\xe9", "Montmartin-en-Graignes", 
"MONTMARTIN-EN-GRAIGNES", "Montmeillant", "MONTMEILLANT", "Montmorillon", 
"Montr\xe9al", "Montreuil-sur-Lozon", "MONTROL-SENARD", "MONTROLLET", 
"MORGNY-EN-THIERACHE", "MORLAC", "Morterolles-sur-Semme", "Morval", 
"MORVILLE", "Morvilliers", "Mosnay", "Mouhers", "MOUHERS", "MOUHET", 
"Moulines", "Moulismes", "MOULISMES", "MOUSSAC", "moussey", "Mousson", 
"Mouterre-sur-Blourde", "MOUTERRE-SUR-BLOURDE", "Moutiers-Saint-Jean", 
"Moyenvic", "Murs", "N\xe9rignac", "NANTIAT", "NANTILLOIS", "Narb\xe9fontaine", 
"NEAUPHE-SUR-DIVE", "NEDONCHEL", "NERONDES", "Neufgrange", "NEUILLAY-LES-BOIS", 
"NEUVILLE-LES-DAMES", "NEUVILLE-LEZ-BEAULIEU", "NEUVILLE-SUR-AUTHOU", 
"Neuville-sur-Touques", "Neuvy-Saint-S\xe9pulchre", "NEUVY-SAINT-SEPULCHRE", 
"NEVILLE-SUR-MER", "Nibas", "NIBAS", "NIBELLE", "Nielles-l\xe8s-Bl\xe9quin", 
"Nieuil", "Niherne", "Nogent", "Noirterre", "Nomain", "Norroy", 
"Notre-Dame-d'\xc9pine", "NOUAILLE-MAUPERTUIS", "Nouans-les-Fontaines", 
"Nouic", "Nully", "Nuret-le-Ferron", "NURET-LE-FERRON", "Ocqueville", 
"OCTEVILLE", "Ollainville", "Oradour-Fanais", "Oradour-Saint-Genest", 
"ORADOUR-SAINT-GENEST", "ORDIARP", "Origny-en-Thi\xe9rache", 
"Origny-Sainte-Beno\xeete", "ORMES", "ORMES-ET-VILLE", "Ormoy", 
"Orsennes", "Orsinval", "ORVILLE", "Osmoy", "OULCHES", "Outines", 
"Outrem\xe9court", "OZERAILLES", "PAGEAS", "PALLUAU-SUR-INDRE", 
"PAREY-SAINT-CESAIRE", "Parfondeval", "PARNAC", "PARTHENAY", 
"PAS-EN-ARTOIS", "Payroux", "PAYROUX", "Pel-et-Der", "Persac", 
"PERSAC", "PETERSBACH", "Peyrat-de-Bellac", "PEYRILHAC", "Pindray", 
"PINDRAY", "PISSY-POVILLE", "PLAISANCE", "Pleuville", "PLOMB", 
"Pommer\xe9val", "POMMIERS", "PONT-FARCY", "PONT-SUR-SAMBRE", 
"Pouillenay", "Pouligny-Notre-Dame", "Pouligny-Saint-Pierre", 
"POULIGNY-SAINT-PIERRE", "Pourrain", "Poursac", "Pouru-aux-Bois", 
"Pr\xe9cy-sous-Thil", "Pr\xe9cy-sur-Vrin", "Pr\xe9ny", "Pr\xe9tot-Sainte-Suzanne", 
"Pr\xe9tot-Vicquemare", "Prangey", "PREMONT", "Pressac", "PRESSAC", 
"Pressignac", "Prissac", "PRISSAC", "Proussy", "Provency", "PROVENCY", 
"Pulligny", "Punerot", "Puttelange-l\xe8s-Thionville", "Qua\xebdypre", 
"Queaux", "QUESTRECQUES", "QUIBOU", "Quoeux-Haut-Mainil", "R\xe9chicourt-la-Petite", 
"R\xe9chicourt-le-Ch\xe2teau", "R\xe9moville", "RADINGHEM", "Radonvilliers", 
"Raffetot", "Ran\xe7onni\xe8res", "Rancon", "RANCON", "Rangecourt", 
"RAUVILLE-LA-BIGOT", "RECHICOURT-LE-CHATEAU", "REMILLY", "REMILLY-SUR-LOZON", 
"Rennepont", "RENNEPONT", "Renneval", "Repel", "RESSON", "REUMONT", 
"Ricarville", "RICHELING", "Rigny-la-Salle", "Rimsdorf", "Rocheville", 
"ROMAGNE", "Romain-sur-Meuse", "Ronch\xe8res", "Rousies", "Roussac", 
"ROUSSAC", "ROUSSINES", "Roussy-le-Village", "Rouvres-sous-Meilly", 
"Rouvrois-sur-Meuse", "ROYERES", "Ruffec", "RUFFEC", "Rumegies", 
"Rupt-devant-Saint-Mihiel", "S\xe9meries", "S\xe9nill\xe9", "Sacierges-Saint-Martin", 
"Saint-\xc9pain", "Saint-Agnan", "SAINT-ALGIS", "Saint-Andr\xe9-de-Bohon", 
"SAINT-ANDRE-LE-BOUCHOUX", "Saint-Ao\xfbt", "SAINT-AOUT", "SAINT-AVRE", 
"Saint-Barbant", "SAINT-BARBANT", "Saint-Bonnet-de-Bellac", "SAINT-BONNET-DE-BELLAC", 
"SAINT-BRICE", "SAINT-CHARTIER", "SAINT-CHRISTOPHE", "SAINT-CHRISTOPHE-EN-BAZELLE", 
"Saint-Clair-sur-les-Monts", "Saint-Cyr-de-Salerne", "Saint-D\xe9sir\xe9", 
"Saint-Denis-de l'H\xf4tel", "SAINT-DENIS-DE-JOUHET", "Saint-Denoeux", 
"SAINT-EBREMOND-DE-BONFOSSE", "Saint-Eustache-la-For\xeat", "SAINT-FIRMIN-DES-BOIS", 
"SAINT-FIRMIN-SUR-LOIRE", "Saint-G\xe2tien-des-Bois", "Saint-Georges", 
"Saint-Georges-d'Elle", "Saint-Georges-les-Landes", "SAINT-GEORGES-LES-LANDES", 
"SAINT-GERMAIN-DE-LIVET", "SAINT-GERMAIN-DES-PRES", "SAINT-GERMAIN-LES-SENAILLY", 
"Saint-Germain-sous-Cailly", "Saint-Germain-sur-Bresle", "Saint-Hilaire-de-Court", 
"SAINT-HILAIRE-EN-LIGNIERES", "SAINT-HILAIRE-EN-MORVAN", "Saint-Hilaire-La-Treille", 
"SAINT-HILAIRE-LA-TREILLE", "Saint-Hilaire-sur-B\xe9naize", "SAINT-HILAIRE-SUR-BENAIZE", 
"SAINT-HIPPOLYTE", "SAINT-JEAN-DE-BOEUF", "Saint-Jean-de-la-Neuville", 
"Saint-Jean-le-Blanc", "SAINT-JOIRE", "Saint-Julien-sur-Sarthe", 
"Saint-Juvin", "Saint-L\xe9ger-Magnazeix", "Saint-L\xe9omer", 
"SAINT-LEGER-DU-BOIS", "SAINT-LEGER-MAGNAZEIX", "SAINT-LEGER-SOUS-CHOLET", 
"SAINT-LEGER-SUR-DHEUNE", "SAINT-LEOMER", "SAINT-LEONARD", "Saint-Lupien", 
"Saint-Martial-sur-Isop", "Saint-Martin-aux-Chartrains", "Saint-Martin-de-Lamps", 
"Saint-Martin-en-Campagne", "Saint-Martin-l'Ars", "SAINT-MARTIN-L'ARS", 
"Saint-Martin-l'Hortier", "Saint-Martin-sur-Ouanne", "Saint-Mary", 
"SAINT-MAUR", "Saint-Maurice-des-Lions", "SAINT-MAURICE-DES-LIONS", 
"Saint-Maurice-la-Clou\xe8re", "SAINT-MAURICE-LA-CLOUERE", "Saint-Maurice-la-Souterraine", 
"SAINT-MAURICE-LA-SOUTERRAINE", "SAINT-MAURICE-SUR-AVEYRON", 
"Saint-Menoux", "SAINT-MICHEL-EN-BRENNE", "Saint-Ouen-l\xe8s-Parey", 
"Saint-Ouen-sur-Gartempe", "SAINT-OUEN-SUR-GARTEMPE", "SAINT-OUEN-SUR-LOIRE", 
"Saint-P\xe8re", "Saint-Pierre-de-Fursac", "Saint-Pierre-de-Maill\xe9", 
"SAINT-PIERRE-DE-MAILLE", "Saint-Pierre-de-Varennes", "Saint-Pierre-le-Vieux", 
"Saint-Pierre-le-Viger", "Saint-Pierremont", "Saint-Priest-Ligoure", 
"SAINT-PRIEST-TAURION", "Saint-Quentin-des-Pr\xe9s", "Saint-S\xe9condin", 
"Saint-Saturnin-du-Bois", "Saint-Saulge", "SAINT-SAUVEUR-LE-VICOMTE", 
"Saint-Sornin-la-Marche", "Saint-Sornin-Leulac", "Saint-Sulpice", 
"Saint-Sulpice-le-Dunois", "Saint-Sulpice-les-Feuilles", "SAINT-SYMPHORIEN", 
"Saint-Symphorien-sur-Couze", "SAINT-THURIEN", "Saint-Vaast-d'\xc9quiqueville", 
"Saint-Val\xe9ry-sur-Somme", "Saint-Victor-sur-Ouche", "Saint-Vincent-Cramesnil", 
"Sainte-Colombe", "SAINTE-COLOMBE-SUR-LOING", "SAINTE-CROIX", 
"Sainte-Croix-aux-Mines", "Sainte-H\xe9l\xe8ne-Bondeville", "Sainte-Maure-de-Touraine", 
"SAINTE-MAURE-DE-TOURAINE", "Sainte-Menehould", "Sainte-Radegonde", 
"Sainte-S\xe9v\xe8re-sur-Indre", "Saints", "SAIZY", "Salon", 
"Sandaucourt", "SANDAUCOURT", "SANGATTE", "Sarcey", "SARDY-LES-EPIRY", 
"SARNOIS", "Sarralbe", "Saulg\xe9", "SAULGOND", "Saulxures", 
"SAULXURES-LES-VANNES", "Sauzelles", "Savigny-en-Terre-Plaine", 
"Savilly", "Schillersdorf", "Schleithal", "Schopperten", "SEMIDE", 
"semoutiers", "Senaide", "Senonges", "Seraumont", "Sermaize-les-Bains", 
"Serqueux", "SERVINS", "Sexey-aux-Forges", "Signy-le-Petit", 
"Sincey", "Sivry", "Sogny-en-l'Angle", "SOIZE", "Sologny", "SOLOGNY", 
"SOMMAING", "Sommeval", "Sorcy-Saint-Martin", "Suisse", "SURIS", 
"Suzanne", "TACONNAY", "TANNAY", "Tannerre-en-Puisaye", "Tendu", 
"TERNAS", "Tersannes", "TERSANNES", "Th\xe9norgues", "Theillay", 
"Thenay", "They-sous-Vaud\xe9mont", "Thiat", "THIEFFRAIN", "THIEULLOY-L'ABBAYE", 
"Thollet", "THOLLET", "Thonne-le-Thil", "Thorey-Lyautey", "Thors", 
"Tign\xe9court", "Tilly-sur-Meuse", "Touffreville-sur-Eu", "Tourlaville", 
"Tourmignies", "Tourni\xe8res", "Tr\xe9mont-sur-Saulx", "Tr\xe9monzey", 
"Tramayes", "Tranzault", "TRANZAULT", "TREVOL", "TUPIGNY", "Uchizy", 
"Urville", "Usson-du-Poitou", "USSON-DU-POITOU", "VACQUERIE-LE-BOUCQ", 
"Vains", "VAINS", "Val-de-Meuse", "Valfroicourt", "VANDENESSE-EN-AUXOIS", 
"Vandy", "VARANGEVILLE", "VARENGUEBEC", "VARESNES", "VARZY", 
"VASLES", "Vaud\xe9mont", "Vaudeville", "VAUDOY-EN-BRIE", "Vaulry", 
"Vault-de-Lugny", "VAUX", "Vaux-sur-Aure", "Vaux-sur-Blaise", 
"VAZEILLES-LIMANDRE", "Velles", "Vendoeuvres", "VENESMES", "VENTES-SAINT-REMY", 
"VERNEUIL", "Verneuil-Moustiers", "VERNEUIL-MOUSTIERS", "Vernon", 
"VERRIERES", "VERTEUIL-SUR-CHARENTE", "Veuvey-sur-Ouche", "Veyrac", 
"VEZELISE", "VIC-DE-CHASSENAY", "VICQ-SUR-GARTEMPE", "Vierzy", 
"Vieux", "Vigneulles", "Vigoux", "VIGOUX", "Vill\xe9cloye", "VILLE-LE-MARCLET", 
"Villemotier", "VILLENTROIS", "VILLERS-AU-BOIS", "Villers-Br\xfblin", 
"Villers-Outr\xe9aux", "VILLEY-SAINT-ETIENNE", "Villiers-le-Sec", 
"VILLIEU-LOYES-MOLLON", "VIMENIL", "Vimoutiers", "VINEUIL", "Vingt-Hanaps", 
"Viriat", "Vironchaux", "Vitrey", "Voncq", "Waldhambach", "WANNEHAIN", 
"Wi\xe8ge-Faty", "WIEGE-FATY", "Wignehies", "WILLERONCOURT", 
"Wimy", "Winnezeele", "Wissant", "Woincourt"), class = "factor"), 
    unit.type = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = "Farm", class = "factor"), 
    location = structure(c(1036L, 548L, 846L, 775L, 122L, 791L
    ), .Label = c("\xc9pen\xe8de", "\xc9perrais", "\xc9poisses", 
    "\xc9riseul", "\xc9tagnac", "\xc9talleville", "\xc9tr\xe9aupont", 
    "\xc9treillers", "\xc9troeungt", "abilly", "Abzac", "ABZAC", 
    "Abzac n\xb01", "Abzac n\xb02", "ACY", "Adriers", "ADRIERS", 
    "Adriers n\xb01", "Adriers n\xb02", "AFFLEVILLE", "Agincourt", 
    "Ailly-le-Haut-Clocher", "Aisey-et-Richecourt", "Aixe-sur-Vienne", 
    "Aizy Jouy", "Alincthun", "ALLICHAMPS", "ALLOUE", "Allouville-Bellefosse", 
    "Ambernac", "Andilly-en-Bassigny", "Andryes", "Angely", "ANOST", 
    "Anrosey", "Ansac-sur-Vienne", "ANSAC-SUR-VIENNE", "ANSAUVILLERS", 
    "Anv\xe9ville", "Archigny", "ARGILLIERES", "ARGY", "ARMES", 
    "Arnac-la-Poste", "Arnac-la-Poste n\xb01", "Arnac-la-Poste n\xb02", 
    "Arrest", "Artannes-sur-Indre", "Asni\xe8res-sur-Blour", 
    "ASNIERES-SUR-BLOUR", "ASPACH", "Attin", "Atton", "Auberville-la-Renault", 
    "AUCHY-LEZ-ORCHIES", "Audincthun", "AUDINGHEN", "Audruicq", 
    "AULT", "Aunay-sur-Odon", "Authe", "Authieule", "Autigny-la-Tour", 
    "Autrey", "AUTREY", "AUXAIS", "Availles-Limouzine", "AVAILLES-LIMOUZINE", 
    "Avelin", "Avermes", "Avesnelles", "AVESNES-LE-SEC", "Avrecourt", 
    "AVROULT", "Awoingt", "AYDOILLES", "AZAT-LE-RIS", "Azay-le-Ferron", 
    "AZAY-LE-FERRON", "AZAY-LE-RIDEAU", "Azoudange", "AZY-LE-VIF", 
    "B\xe9court", "B\xe9nouville", "B\xe9thines", "Bacourt", 
    "Bacqueville-en-Caux", "Bagneux", "Bailleul", "BAINVILLE-SUR-MADON", 
    "BALLAY", "Balledent", "BALLEDENT", "Baons-le-Comte", "BARBAS", 
    "Basse-sur-le-Rupt", "Bauzemont", "BAVINCOURT", "Bay-sur Aube", 
    "BAZELAT", "BEAULIEU", "Beauquesne", "Beaurepaire", "Beaurepaire-en-Bresse", 
    "Beauvilliers", "BEGROLLES-EN-MAUGES", "Bellac", "Belrupt", 
    "Belval-sous-Ch\xe2tillon", "BERCK", "BEREZIAT", "Berneuil", 
    "Bernouville", "BERTHEN", "BERUGES", "BESSINES-SUR-GARTEMPE", 
    "BETHINES", "Bettoncourt-le-Haut", "Beurizot", "Beurville", 
    "Beux", "Beuzeville", "Beuzeville-la-Grenier", "Bezaumont", 
    "Biarre", "Billy-sous-les-C\xf4tes", "BISLEE", "Bissey-sous-Cruchaud", 
    "Biville-la-Baignarde", "BIZIAT", "BLANCHEFOSSE-ET-BAY", 
    "Blanzac", "BLANZAC", "BLARINGHEM", "Blessonville", "Blicourt", 
    "Blond", "Bolbec", "Bolleville", "Bonneuil", "Bonneuil n\xb01", 
    "Bonneuil n\xb02", "Bonny-sur-Loire", "Bossancourt", "BOUESSE", 
    "Bougey", "BOULAY-MOSELLE", "Bourbonne-les-Bains", "Bouresse", 
    "BOURESSE", "Bourg-Archambault", "BOURG-ARCHAMBAULT", "Boz", 
    "Br\xe9aut\xe9", "Br\xe9m\xe9nil", "Br\xe9moncourt", "Braux", 
    "BREVES", "Briantes", "Bricquebec", "BRICQUEBEC", "Brigueil-le-Chantre", 
    "BRIGUEIL-LE-CHANTRE", "Brigueil-le-Chantre n\xb01", "Brigueil-le-Chantre n\xb02", 
    "Brigueuil", "BRIGUEUIL", "Brillac", "BRILLAC", "BRIXEY-AUX-CHANOINES", 
    "Brulange", "Brunehamel", "Brutelles", "Bucamps", "Buffign\xe9court", 
    "Buhl-Lorraine", "BURTHECOURT-AUX-CHENES", "Bussi\xe8re-Poitevine", 
    "BUSSIERE-BOFFY", "BUSSIERE-POITEVINE", "Buxi\xe8res-d'Aillac", 
    "BUXIERES-LES-MINES", "C\xe9lon", "CABANAC-ET-VILLAGRAINS", 
    "Cambremer", "Cannectancourt", "Canville-les-Deux-\xc9glises", 
    "Carignan", "Carignan bis", "CARQUEBUT", "CATIGNY", "Catillon-sur-Sambre", 
    "Caunay", "Cavron-Saint-Martin", "CERE-LA-RONDE", "CERENCES", 
    "CERISY-LA-SALLE", "Ch\xe2teau-Garnier", "Ch\xe2teau-Garnier n\xb01", 
    "Ch\xe2teau-Garnier n\xb02", "ch\xe2teau-salins", "Ch\xe2teauponsac", 
    "Ch\xe2tenay-Vaudin", "Ch\xe2tenay-Vaudin n\xb01", "Ch\xe2tenois", 
    "Ch\xe9zeaux", "Ch\xe9zy-en-Orxois", "Chablis", "CHABRIS", 
    "Chaillac", "CHAILLAC", "Chaillac n\xb01", "Chaillac n\xb02", 
    "Chaillac n\xb03", "CHAILLAC-SUR-VIENNE", "Chailly-sur-Arman\xe7on", 
    "CHALAIS", "Chalindrey", "CHALLERANGE", "CHAMARANDES-CHOIGNES", 
    "Chamboret", "Chambrey", "CHAMPAGNE-SAINT-HILAIRE", "Champigny-sous-Varennes", 
    "CHAMPS", "CHAMPSEVRAINE", "Chantelle", "Chaouilley", "Charbuy", 
    "CHARLEVILLE-SOUS-BOIS", "Charmes-la-Grande", "CHARMES-LA-GRANDE", 
    "charroux", "Chassey-l\xe8s-Montbozon", "CHATEAU-CHINON(CAMPAGNE)", 
    "CHATEAU-GARNIER", "CHATEAUPONSAC", "Chaudenay", "CHAUMONT-LA-VILLE", 
    "Chaumont-Porcien", "Chauvigny", "CHAVEYRIAT", "Chazelet", 
    "CHAZELLES", "CHEHERY", "Chemery", "CHEMERY", "Chemin-d'Aisey", 
    "CHENIERS", "Cherbourg", "CHERVES-CHATELARS", "Chevannes", 
    "CHEVERNY", "Chevillon", "CHEVROCHES", "Chicourt", "CHIRAC", 
    "Cieux", "Ciron", "Civrieux", "Cizay-la-Madeleine", "Cl\xe9rey-sur-Br\xe9non", 
    "Cl\xe9zentaine", "CLAIRFONTAINE", "Clamecy", "CLAMECY", 
    "CLERE-DU-BOIS", "Clinchamps-sur-Orne", "CLION", "Coiffy-le-Haut", 
    "COINGT", "Colombey-les-Belles", "COLOMBEY-LES-DEUX-EGLISES", 
    "COLONDANNES", "Combres-sous-les-C\xf4tes", "COMBREUX", "Cond\xe9-Northen", 
    "CONDE-NORTHEN", "CONFOLENS", "Confran\xe7on", "CONGE-SUR-ORNE", 
    "Conthil", "Corpoyer-la-Chapelle", "COSSAYE", "Cossesseville", 
    "Coulandon", "COULLEMONT", "Coulmier-le-Sec", "Coulonges", 
    "COULONGES", "COULONGES n\xb01", "COULONGES n\xb02", "Coulonges-sur-Sarthe", 
    "Coupelle-Vieille", "COURCELLES-LES-SEMUR", "COURGEON", "COURTESOULT-ET-GATEY", 
    "Coussay-les-Bois", "COUVERTPUIS", "Coyviller", "Cr\xe9quy", 
    "CRECY-SUR-SERRE", "CREQUY", "CRIEL-SUR-MER", "Crion", "CROISY", 
    "CROMAC", "CRUGNY", "Crupilly", "CULAN", "Cussay", "Cuves", 
    "D\xe9deling", "Dammartin-sur-Meuse", "Darnac", "DARNAC", 
    "Delettes", "DELETTES", "Dercy", "Desvres", "DIEVAL", "Dinsac", 
    "DOMBROT-SUR-VAIR", "Domecy-sur-Cure", "Domgermain", "Domjulien", 
    "DOMMARTIN-DAMPIERRE", "Dompierre-les-\xc9glises", "Dompierre-sur-Authie", 
    "Domptail", "Donzy", "Doudeauville", "Douvrend", "DOVILLE", 
    "Dracy", "Dracy-Saint-Loup", "Drambon", "Droisy", "Droux", 
    "Dunet", "ECUEILLE", "ECUIRES", "ECULLEVILLE", "Emberm\xe9nil", 
    "Empur\xe9", "Englesqueville-en-Auge", "Envronville", "EPAIGNES", 
    "epinac", "EPINAL", "Escles", "Escombres-et-le-Chesnois", 
    "Esley", "Esse", "ESSE", "Esse n\xb01", "Esse n\xb02", "Euilly-et-Lombut n\xb01", 
    "Euilly-et-Lombut n\xb02", "EXIDEUIL", "Eywiller", "FAULQUEMONT", 
    "Faulx", "FAULX", "Faveraye-Machelles", "FAYE-L'ABBESSE", 
    "FAYL-BILLOT", "FEYTIAT", "Fill\xe9", "FLAGEY", "Fleury-la-For\xeat", 
    "FLIGNY", "Flor\xe9mont", "Fluqui\xe8res", "FOAMEIX-ORNEL", 
    "Fontaine-au-Bois", "Fontaine-l\xe8s-Vervins", "Fontaine-le-Dun", 
    "FONTAINE-LES-VERVINS", "Fontaines", "Fontangy", "FONTENELLE", 
    "formigny", "Fossieux", "Foucart", "Foulcrey", "Fouligny", 
    "Fourcigny", "FOURS", "Fr\xe9monville", "Fr\xe9vent", "Fr\xf4lois", 
    "Fraignot-et-Vesvrotte", "Framicourt", "Fraquelfing", "Freb\xe9court", 
    "Frenelle-la-Grande", "Freneuse-sur-Risle", "Fresnes-en-Saulnois", 
    "Fresnes-en-Tardenois", "FRESNOY-FOLNY", "Fromy", "FRONTENARD", 
    "G\xe9lucourt", "GAJOUBERT", "GARGILESSE-DAMPIERRE", "Gemmelaincourt", 
    "GEMONVILLE", "Genouillac", "Gerb\xe9viller", "Gergny", "GERMINY", 
    "Gevrolles", "Ghyvelde", "GIEVILLE", "ginai", "Giraumont", 
    "Givron n\xb01", "Givron n\xb02", "Gizay", "Glanges", "GLOS-LA-FERRIERE", 
    "GODERVILLE", "GOLLEVILLE", "GONCOURT", "Gonneville", "GONNEVILLE-EN-AUGE", 
    "Gouberville", "Gouex", "GOUEX", "Gournay", "GOURNAY-EN-BRAY", 
    "Goviller", "Grand", "Grand Rullecourt", "GRAND-CAMP", "Grandcourt", 
    "Greuville", "GREZ", "Grez-en-Bou\xe8re", "Grivy-Loisy", 
    "GROSSOUVRE", "Grosville", "Gu\xe9bling", "GUILLON", "Guilly", 
    "Guincourt", "GUIPY", "H\xe9nam\xe9nil", "Haboudange", "Haillainville", 
    "Hambye", "Hammeville", "HANNACHES", "HARGICOURT", "Hary", 
    "HAUT-LIEU", "HAUTE-AMANCE", "Haute-Kontz", "HAUTEFONTAINE", 
    "Hauteroche", "HAUTTEVILLE-BOCAGE", "HAZEBROUCK", "Hennezel", 
    "Hermanville", "Heugleville-sur-Scie", "HEUGNES", "Honnechy", 
    "Honskirch", "HORNAING", "HORNOY-LE-BOURG", "Hou\xe9ville", 
    "Houdelaincourt", "HOUECOURT", "Hugleville-en-Caux", "Hurecourt", 
    "Ibigny", "ILLKIRCH-GRAFFENSTADEN", "Imbleville", "Incourt", 
    "INCOURT", "Insming", "Is-en-Bassigny", "ISENAY", "Jaulges", 
    "Jeantes", "JEANTES", "JEU-LES-BOIS", "Jouac", "Jouhet", 
    "JOUHET", "JOURNET", "JOUSSE", "JUGY", "JUVIGNIES", "KIRRWILLER-BOSSELSHAUSEN", 
    "L'\xc9tang-Bertrand", "L'Isle-Jourdain n\xb01", "L'Isle-Jourdain n\xb02", 
    "La Bazeuge", "LA BERTHENOUX", "LA BESACE", "La Blouti\xe8re", 
    "La Celle-Gu\xe9nand", "LA CELLE-SUR-LOIRE", "La Cerlangue", 
    "La Chapelle-Bertrand", "La Chapelle-Montreuil", "LA CHAPELLE-MONTREUIL", 
    "La Chapelle-Th\xe8cle", "LA COLOMBE", "LA COMTE", "LA COURBE", 
    "La Croix-sur-Gartempe", "LA CROIX-SUR-GARTEMPE", "LA FEREE", 
    "LA FERMETE", "La Ferri\xe8re-en-Parthenay", "La Fert\xe9-Loupi\xe8re", 
    "La Gaillarde", "La Godefroy", "La Haye-du-Puits", "La Loge", 
    "LA MANCELIERE", "La Mothe-Saint-H\xe9ray", "La P\xe9rouille", 
    "LA PERCHE", "LA PERNELLE", "LA PUYE", "La Roche-Chalais", 
    "La Roche-en-Brenil", "La Roche-Posay", "LA ROCHE-VANNEAU", 
    "La Souterraine", "LA SUZE-SUR-SARTHE", "La Trimouille", 
    "LA TRIMOUILLE", "La Trimouille n\xb01", "La Trimouille n\xb02", 
    "La Vineuse", "Lagarde", "Laitre-sous-Amance", "Lamarche", 
    "Landange", "LANDOUZY-LA-VILLE", "LANGRUNE-SUR-MER", "LANTAGES", 
    "LATHUS-SAINT-REMY", "LATHUS-SAINT-REMY n\xb01", "LATHUS-SAINT-REMY n\xb02", 
    "Launstroff", "Lavall\xe9e", "LAVAUSSEAU", "Le B\xe9ny-Bocage", 
    "Le Blanc", "LE BLANC", "Le Bourg-d'Hem", "LE CATEAU-CAMBRESIS", 
    "LE CHATELET", "LE DORAT", "Le Doulieu", "Le F\xeate", "LE LOUROUX", 
    "LE MAY-SUR-EVRE", "LE MENIL-GUYON", "Le Mesnil-Eudes", "Le Mesnil-Raoult", 
    "LE MESNIL-ROGUES", "Le Mesnilbus", "Le Nouvion-en-Thi\xe9rache", 
    "LE PECHEREAU", "LE PIN", "LE PLESSIER-SUR-BULLES", "Le Reculey", 
    "LE SOUICH", "Le Torpt", "Le Val-Saint-P\xe8re", "Le Vigeant", 
    "LE VIGEANT", "Le Vigeant n\xb01", "Le Vigeant n\xb02", "Le Vr\xe9tot", 
    "Leignes-sur-Fontaine", "Leintrey", "Lengronne", "LENT", 
    "Les Forges", "Les Grands Ch\xe9zeaux", "LES LOGES", "Les Thons", 
    "LES TROIS-PIERRES", "LESMENILS", "Lessac", "Lesterps", "LEULINGHEM", 
    "Levoncourt n\xb01", "Levoncourt n\xb02", "Levroux", "Liernais", 
    "LIESVILLE-SUR-DOUVE", "LIFFOL-LE-GRAND", "Liglet", "LIGLET", 
    "Lignac", "LIGNAC", "Lignac n\xb01", "Lignac n\xb02", "LIGNEREUIL", 
    "LIGNIERES-CHATELAIN", "Lignol-le-Ch\xe2teau", "LIMANTON", 
    "LIMOGES", "Limonest", "Linselles", "Lironville", "LIVERDUN", 
    "Lochwiller", "Loison", "Long", "Longeville-en-Barrois", 
    "Longeville-sur-la-Laines", "Longpr\xe9-les-Corps-Saints", 
    "Longvillers", "LORMES", "Lottinghen", "Louvencourt", "Louvi\xe8res", 
    "Lu\xe7ay-le-M\xe2le", "LUANT", "LUCE-SOUS-BALLON", "Luchapt", 
    "Lussac", "LUSSAC", "Lussac-les-\xc9glises", "Lussac-les-Ch\xe2teaux", 
    "LUSSAC-LES-EGLISES", "Luttange", "LUZERET", "LYE", "M\xe9nil-en-Xaintois", 
    "M\xe9nil-sur-Belvitte", "M\xe9obecq", "M\xe9ry-la-Bataille", 
    "M\xe9zi\xe8res-sur-Issoire", "Magnac-Laval", "MAGNAC-LAVAL", 
    "Magneville", "Magny", "Magny-le-Freule", "Mailhac-sur-Benaize", 
    "MAILHAC-SUR-BENAIZE", "MAILLET", "Mailly-sur-Seille", "MAISON-MAUGIS", 
    "MAISONCELLE-TUILERIE", "Maixe", "Maizi\xe8res", "Malaincourt-sur-Meuse", 
    "MALICORNAY", "Man\xe9houville", "MANDRES-EN-BARROIS", "Manerbe", 
    "Manglieu", "MANNEVILLE-LA-PIPARD", "Manoncourt-en-Vermois", 
    "Manoncourt-sur-Seille", "MARAINVILLER", "MARANGE-ZONDRANGE", 
    "Marault", "Marchais-en-Brie", "MARCHESEUIL", "Marcilly-en-Bassigny", 
    "MARCILLY-EN-BASSIGNY", "MARIGNY", "MARIGNY-BRIZAY", "Marigny-l'\xc9glise", 
    "Marnay", "Martigny", "Martincourt", "MARTIZAY", "Marville", 
    "Marzy", "MASSIGNAC", "Mattexey", "Maupr\xe9voir", "MAUPREVOIR", 
    "MAUX", "Mavilly-Mandelot", "Mazerolles", "Mazingarbe", "Meillant", 
    "MELLEROY", "MENETOU-RATEL", "MENEVILLERS", "MERLAUT", "Mers-sur-Indre", 
    "MERS-SUR-INDRE", "Mesnil-Domqueur", "Metz-Robert", "Meuvy", 
    "Mietesheim", "MILLERY", "MIRECOURT", "MISSE", "MONCEAU-SAINT-WAAST", 
    "MONCHIET", "Mons-Boubert", "MONS-EN-LAONNOIS", "Mont-Bonvillers", 
    "MONT-ET-MARRE", "MONT-LES-LAMARCHE", "Montauban-de-Picardie", 
    "MONTBOUY", "MONTCAVREL", "MONTCHEVRIER", "Montheries", "Montiers-sur-Saulx", 
    "MONTIERS-SUR-SAULX", "MONTIGNY-EN-CAMBRESIS", "Montigny-l\xe8s-Vaucouleurs", 
    "Montigny-Montfort", "Montlou\xe9", "Montmartin-en-Graignes", 
    "MONTMARTIN-EN-GRAIGNES", "Montmeillant", "MONTMEILLANT", 
    "Montmorillon", "Montr\xe9al", "Montreuil-sur-Lozon", "MONTROL-SENARD", 
    "MONTROLLET", "MORGNY-EN-THIERACHE", "MORLAC", "Morterolles-sur-Semme", 
    "Morval", "MORVILLE", "Morvilliers", "Mosnay", "Mouhers", 
    "MOUHERS", "MOUHET", "Moulines", "Moulismes", "MOULISMES", 
    "Moulismes n\xb01", "Moulismes n\xb02", "MOUSSAC", "moussey", 
    "Mousson", "Mouterre-sur-Blourde", "MOUTERRE-SUR-BLOURDE", 
    "Moutiers-Saint-Jean", "Moyenvic", "Murs", "N\xe9rignac", 
    "NANTIAT", "NANTILLOIS", "Narb\xe9fontaine", "NEAUPHE-SUR-DIVE", 
    "NEDONCHEL", "NERONDES", "Neufgrange", "NEUILLAY-LES-BOIS", 
    "NEUVILLE-LES-DAMES", "NEUVILLE-LEZ-BEAULIEU", "NEUVILLE-SUR-AUTHOU", 
    "Neuville-sur-Touques", "Neuvy-Saint-S\xe9pulchre", "NEUVY-SAINT-SEPULCHRE", 
    "NEVILLE-SUR-MER", "Nibas", "NIBAS", "NIBELLE", "Nielles-l\xe8s-Bl\xe9quin", 
    "Nieuil", "Niherne", "Nogent", "Noirterre", "Nomain", "Norroy", 
    "Notre-Dame-d'\xc9pine", "NOUAILLE-MAUPERTUIS", "Nouans-les-Fontaines", 
    "Nouic", "Nully", "Nuret-le-Ferron", "NURET-LE-FERRON", "Ocqueville", 
    "OCTEVILLE", "Ollainville", "Oradour-Fanais", "Oradour-Saint-Genest", 
    "ORADOUR-SAINT-GENEST", "ORDIARP", "Origny-en-Thi\xe9rache", 
    "Origny-Sainte-Beno\xeete", "ORMES", "ORMES-ET-VILLE", "Ormoy", 
    "Orsennes", "Orsinval", "ORVILLE", "Osmoy", "OULCHES", "Outines", 
    "Outrem\xe9court", "OZERAILLES", "PAGEAS", "PALLUAU-SUR-INDRE", 
    "PAREY-SAINT-CESAIRE", "Parfondeval", "PARNAC", "PARTHENAY", 
    "PAS-EN-ARTOIS", "Payroux", "PAYROUX", "Pel-et-Der", "Persac", 
    "PERSAC", "PETERSBACH", "Peyrat-de-Bellac", "PEYRILHAC", 
    "PINDRAY", "Pindray n\xb01", "Pindray n\xb02", "PISSY-POVILLE", 
    "PLAISANCE", "Pleuville", "PLOMB", "Pommer\xe9val", "POMMIERS", 
    "PONT-FARCY", "PONT-SUR-SAMBRE", "Pouillenay", "Pouligny-Notre-Dame", 
    "Pouligny-Saint-Pierre", "POULIGNY-SAINT-PIERRE", "Pourrain", 
    "Poursac", "Pouru-aux-Bois", "Pr\xe9cy-sous-Thil", "Pr\xe9cy-sur-Vrin", 
    "Pr\xe9ny", "Pr\xe9tot-Sainte-Suzanne", "Pr\xe9tot-Vicquemare", 
    "Prangey", "PREMONT", "Pressac", "PRESSAC", "Pressignac", 
    "Prissac", "PRISSAC", "Proussy", "Provency", "PROVENCY", 
    "Pulligny", "Punerot", "Puttelange-l\xe8s-Thionville", "Qua\xebdypre", 
    "Queaux", "QUESTRECQUES", "QUIBOU", "Quoeux-Haut-Mainil", 
    "R\xe9chicourt-la-Petite", "R\xe9chicourt-le-Ch\xe2teau", 
    "R\xe9moville", "RADINGHEM", "Radonvilliers", "Raffetot", 
    "Ran\xe7onni\xe8res", "Rancon", "RANCON", "Rangecourt", "RAUVILLE-LA-BIGOT", 
    "RECHICOURT-LE-CHATEAU", "REMILLY", "REMILLY-SUR-LOZON", 
    "Rennepont", "RENNEPONT", "Renneval", "Repel", "RESSON", 
    "REUMONT", "Ricarville", "RICHELING", "Rigny-la-Salle", "Rimsdorf", 
    "Rocheville", "ROMAGNE", "Romain-sur-Meuse", "Ronch\xe8res", 
    "Rousies", "Roussac", "ROUSSAC", "ROUSSINES", "Roussy-le-Village", 
    "Rouvres-sous-Meilly", "Rouvrois-sur-Meuse", "ROYERES", "RUFFEC", 
    "Ruffec n\xb01", "Ruffec n\xb02", "Rumegies", "Rupt-devant-Saint-Mihiel", 
    "S\xe9meries", "S\xe9nill\xe9", "Sacierges-Saint-Martin", 
    "Saint-\xc9pain", "Saint-Agnan", "SAINT-ALGIS", "Saint-Andr\xe9-de-Bohon", 
    "SAINT-ANDRE-LE-BOUCHOUX", "Saint-Ao\xfbt", "SAINT-AOUT", 
    "SAINT-AVRE", "Saint-Barbant", "SAINT-BARBANT", "Saint-Bonnet-de-Bellac", 
    "SAINT-BONNET-DE-BELLAC", "Saint-Bonnet-de-Bellac n\xb01", 
    "Saint-Bonnet-de-Bellac n\xb02", "SAINT-BRICE", "SAINT-CHARTIER n\xb01", 
    "SAINT-CHARTIER n\xb02", "SAINT-CHRISTOPHE", "SAINT-CHRISTOPHE-EN-BAZELLE", 
    "Saint-Clair-sur-les-Monts", "Saint-Cyr-de-Salerne", "Saint-D\xe9sir\xe9", 
    "Saint-Denis-de l'H\xf4tel", "SAINT-DENIS-DE-JOUHET", "Saint-Denoeux", 
    "SAINT-EBREMOND-DE-BONFOSSE", "Saint-Eustache-la-For\xeat", 
    "SAINT-FIRMIN-DES-BOIS", "SAINT-FIRMIN-SUR-LOIRE", "Saint-G\xe2tien-des-Bois", 
    "Saint-Georges", "Saint-Georges-d'Elle", "SAINT-GEORGES-LES-LANDES", 
    "Saint-Georges-les-Landes n\xb01", "Saint-Georges-les-Landes n\xb02", 
    "SAINT-GERMAIN-DE-LIVET", "SAINT-GERMAIN-DES-PRES", "SAINT-GERMAIN-LES-SENAILLY", 
    "Saint-Germain-sous-Cailly", "Saint-Germain-sur-Bresle", 
    "Saint-Hilaire-de-Court", "SAINT-HILAIRE-EN-LIGNIERES", "SAINT-HILAIRE-EN-MORVAN", 
    "Saint-Hilaire-La-Treille", "SAINT-HILAIRE-LA-TREILLE", "Saint-Hilaire-sur-B\xe9naize", 
    "SAINT-HILAIRE-SUR-BENAIZE", "SAINT-HIPPOLYTE", "SAINT-JEAN-DE-BOEUF", 
    "Saint-Jean-de-la-Neuville", "Saint-Jean-le-Blanc", "SAINT-JOIRE", 
    "Saint-Julien-sur-Sarthe", "Saint-Juvin", "Saint-L\xe9ger-Magnazeix", 
    "Saint-L\xe9ger-Magnazeix n\xb01", "Saint-L\xe9ger-Magnazeix n\xb02", 
    "Saint-L\xe9omer", "SAINT-LEGER-DU-BOIS", "SAINT-LEGER-MAGNAZEIX", 
    "SAINT-LEGER-SOUS-CHOLET", "SAINT-LEGER-SUR-DHEUNE", "SAINT-LEOMER", 
    "SAINT-LEONARD", "Saint-Lupien", "Saint-Martial-sur-Isop", 
    "Saint-Martin-aux-Chartrains", "Saint-Martin-de-Lamps", "Saint-Martin-en-Campagne", 
    "Saint-Martin-l'Ars", "SAINT-MARTIN-L'ARS", "Saint-Martin-l'Hortier", 
    "Saint-Martin-sur-Ouanne", "Saint-Mary", "SAINT-MAUR", "Saint-Maurice-des-Lions", 
    "Saint-Maurice-des-Lions n\xb01", "Saint-Maurice-des-Lions n\xb02", 
    "Saint-Maurice-la-Clou\xe8re", "SAINT-MAURICE-LA-CLOUERE", 
    "Saint-Maurice-la-Souterraine", "SAINT-MAURICE-LA-SOUTERRAINE", 
    "SAINT-MAURICE-SUR-AVEYRON", "Saint-Menoux", "SAINT-MICHEL-EN-BRENNE", 
    "Saint-Ouen-l\xe8s-Parey", "Saint-Ouen-sur-Gartempe", "SAINT-OUEN-SUR-GARTEMPE", 
    "SAINT-OUEN-SUR-LOIRE", "Saint-P\xe8re", "Saint-Pierre-de-Fursac", 
    "Saint-Pierre-de-Maill\xe9", "SAINT-PIERRE-DE-MAILLE", "Saint-Pierre-de-Varennes", 
    "Saint-Pierre-le-Vieux", "Saint-Pierre-le-Viger", "Saint-Pierremont", 
    "Saint-Priest-Ligoure", "SAINT-PRIEST-TAURION", "Saint-Quentin-des-Pr\xe9s", 
    "Saint-S\xe9condin", "Saint-Saturnin-du-Bois", "Saint-Saulge", 
    "SAINT-SAUVEUR-LE-VICOMTE", "Saint-Sornin-la-Marche", "Saint-Sornin-Leulac", 
    "Saint-Sulpice", "Saint-Sulpice-le-Dunois", "Saint-Sulpice-les-Feuilles", 
    "SAINT-SYMPHORIEN", "Saint-Symphorien-sur-Couze", "SAINT-THURIEN", 
    "Saint-Vaast-d'\xc9quiqueville", "Saint-Val\xe9ry-sur-Somme", 
    "Saint-Victor-sur-Ouche", "Saint-Vincent-Cramesnil", "Sainte-Colombe", 
    "SAINTE-COLOMBE-SUR-LOING", "SAINTE-CROIX", "Sainte-Croix-aux-Mines", 
    "Sainte-H\xe9l\xe8ne-Bondeville", "Sainte-Maure-de-Touraine", 
    "SAINTE-MAURE-DE-TOURAINE", "Sainte-Menehould", "Sainte-Radegonde", 
    "Sainte-S\xe9v\xe8re-sur-Indre", "Saints", "SAIZY", "Salon", 
    "Sandaucourt", "SANDAUCOURT", "SANGATTE", "Sarcey", "SARDY-LES-EPIRY", 
    "SARNOIS", "Sarralbe", "Saulg\xe9", "Saulg\xe9 n\xb01", "Saulg\xe9 n\xb02", 
    "Saulg\xe9 n\xb03", "Saulg\xe9 n\xb04", "Saulg\xe9 n\xb05", 
    "SAULGOND", "Saulxures", "SAULXURES-LES-VANNES", "Sauzelles", 
    "Savigny-en-Terre-Plaine", "Savilly", "Schillersdorf", "Schleithal", 
    "Schopperten", "SEMIDE", "semoutiers", "Senaide", "Senonges", 
    "Seraumont", "Sermaize-les-Bains", "Serqueux", "SERVINS", 
    "Sexey-aux-Forges", "Signy-le-Petit", "Sincey", "Sivry", 
    "Sivry n\xb02", "Sogny-en-l'Angle", "SOIZE", "Sologny", "SOLOGNY", 
    "SOMMAING", "Sommeval", "Sorcy-Saint-Martin", "Suisse", "SURIS", 
    "Suzanne", "TACONNAY", "TANNAY", "Tannerre-en-Puisaye", "Tendu", 
    "TERNAS", "Tersannes", "TERSANNES", "Th\xe9norgues", "Theillay", 
    "Thenay", "They-sous-Vaud\xe9mont", "Thiat", "THIEFFRAIN", 
    "THIEULLOY-L'ABBAYE", "Thollet", "THOLLET", "Thonne-le-Thil", 
    "Thorey-Lyautey", "Thors", "Tign\xe9court", "Tilly-sur-Meuse", 
    "Touffreville-sur-Eu", "Tourlaville", "Tourmignies", "Tourni\xe8res", 
    "Tr\xe9mont-sur-Saulx", "Tr\xe9monzey", "Tramayes", "Tranzault", 
    "TRANZAULT", "TREVOL", "TUPIGNY", "Uchizy", "Urville", "Usson-du-Poitou", 
    "USSON-DU-POITOU", "VACQUERIE-LE-BOUCQ", "Vains", "VAINS", 
    "Val-de-Meuse", "Valfroicourt", "VANDENESSE-EN-AUXOIS", "Vandy", 
    "VARANGEVILLE", "VARENGUEBEC", "VARESNES", "VARZY", "VASLES", 
    "Vaud\xe9mont", "Vaudeville", "VAUDOY-EN-BRIE", "Vaulry", 
    "Vault-de-Lugny", "VAUX", "Vaux-sur-Aure", "Vaux-sur-Blaise", 
    "VAZEILLES-LIMANDRE", "Velles", "Vendoeuvres", "VENESMES", 
    "VENTES-SAINT-REMY", "VERNEUIL", "Verneuil-Moustiers", "VERNEUIL-MOUSTIERS", 
    "Vernon", "VERRIERES", "VERTEUIL-SUR-CHARENTE", "Veuvey-sur-Ouche", 
    "Veyrac", "VEZELISE", "VIC-DE-CHASSENAY", "VICQ-SUR-GARTEMPE", 
    "Vierzy", "Vieux", "Vigneulles", "Vigoux", "VIGOUX", "Vill\xe9cloye", 
    "VILLE-LE-MARCLET", "Villemotier", "VILLENTROIS", "VILLERS-AU-BOIS", 
    "Villers-Br\xfblin", "Villers-Outr\xe9aux", "VILLEY-SAINT-ETIENNE", 
    "Villiers-le-Sec", "VILLIEU-LOYES-MOLLON", "VIMENIL", "Vimoutiers", 
    "VINEUIL", "Vingt-Hanaps", "Viriat", "Vironchaux", "Vitrey", 
    "Voncq", "Waldhambach", "WANNEHAIN", "Wi\xe8ge-Faty", "WIEGE-FATY", 
    "Wignehies", "WILLERONCOURT", "Wimy", "Winnezeele", "Wissant", 
    "Woincourt"), class = "factor"), latitude = c(48.633333, 
    46.383333, 47.733333, 45.883333, 49.333333, 46.116667), longitude = c(4, 
    0.883333, 5.266667, 0.5, 0.35, 0.783333), start.date = structure(c(57L, 
    57L, 57L, 57L, 57L, 57L), .Label = c("01/02/2012", "01/03/2012", 
    "01/04/2012", "02/02/2012", "02/03/2012", "02/04/2012", "03/02/2012", 
    "03/03/2012", "03/04/2012", "04/03/2012", "04/04/2012", "05/02/2012", 
    "05/03/2012", "05/04/2012", "06/02/2012", "06/03/2012", "06/04/2012", 
    "07/02/2012", "07/03/2012", "07/04/2012", "08/02/2012", "08/03/2012", 
    "08/04/2012", "09/02/2012", "09/03/2012", "09/04/2012", "10/02/2012", 
    "10/03/2012", "10/04/2012", "11/02/2012", "11/03/2012", "11/04/2012", 
    "12/02/2012", "12/03/2012", "12/04/2012", "13/02/2012", "13/03/2012", 
    "13/04/2012", "14/02/2012", "14/03/2012", "14/04/2012", "15/02/2012", 
    "15/03/2012", "15/04/2012", "16/02/2012", "16/03/2012", "16/04/2012", 
    "17/02/2012", "17/03/2012", "17/04/2012", "18/02/2012", "18/03/2012", 
    "18/04/2012", "19/02/2012", "19/03/2012", "19/04/2012", "20/01/2012", 
    "20/02/2012", "20/03/2012", "20/04/2012", "21/01/2012", "21/02/2012", 
    "21/03/2012", "22/02/2012", "22/03/2012", "23/01/2012", "23/02/2012", 
    "23/03/2012", "23/04/2012", "24/01/2012", "24/02/2012", "24/03/2012", 
    "25/01/2012", "25/02/2012", "25/03/2012", "26/01/2012", "26/02/2012", 
    "26/03/2012", "27/02/2012", "27/03/2012", "28/02/2012", "28/03/2012", 
    "29/02/2012", "29/03/2012", "30/01/2012", "30/03/2012", "31/01/2012", 
    "31/03/2012"), class = "factor"), sheep.measuring.units = structure(c(1L, 
    1L, 1L, 1L, NA, 1L), .Label = "Animals", class = "factor"), 
    sheep.susceptible = c(NA_integer_, NA_integer_, NA_integer_, 
    NA_integer_, NA_integer_, NA_integer_), sheep.cases = c(NA_integer_, 
    NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_
    ), sheep.deaths = c(NA_integer_, NA_integer_, NA_integer_, 
    NA_integer_, NA_integer_, NA_integer_), sheep.destroyed = c(NA_integer_, 
    NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_
    ), sheep.slaughtered = c(NA_integer_, NA_integer_, NA_integer_, 
    NA_integer_, NA_integer_, NA_integer_), cattle.measuring.units = structure(c(NA, 
    NA, NA, NA, 1L, NA), .Label = "Animals", class = "factor"), 
    cattle.susceptible = c(NA, NA, NA, NA, NA, NA), cattle.cases = c(NA, 
    NA, NA, NA, NA, NA), cattle.deaths = c(NA, NA, NA, NA, NA, 
    NA), cattle.destroyed = c(NA, NA, NA, NA, NA, NA), cattle.slaughtered = c(NA, 
    NA, NA, NA, NA, NA), goat.measuring.units = structure(c(NA_integer_, 
    NA_integer_, NA_integer_, NA_integer_, NA_integer_, NA_integer_
    ), .Label = "Animals", class = "factor"), goat.susceptible = c(NA, 
    NA, NA, NA, NA, NA), goat.cases = c(NA, NA, NA, NA, NA, NA
    ), goat.deaths = c(NA, NA, NA, NA, NA, NA), goat.destroyed = c(NA, 
    NA, NA, NA, NA, NA), goat.slaughtered = c(NA, NA, NA, NA, 
    NA, NA), remark = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Affected Population", 
    "Affected Population newborn lamb", "Affected Population newborn lambs"
    ), class = "factor"), code = structure(c(10L, 87L, 53L, 16L, 
    26L, 16L), .Label = c("01", "02", "03", "04", "05", "06", 
    "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", 
    "17", "18", "19", "21", "22", "23", "24", "25", "26", "27", 
    "28", "29", "2A", "2B", "30", "31", "32", "33", "34", "35", 
    "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", 
    "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", 
    "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", 
    "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", 
    "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", 
    "86", "87", "88", "89", "90", "91", "92", "93", "94", "95"
    ), class = "factor")), .Names = c("departement", "commune", 
"unit.type", "location", "latitude", "longitude", "start.date", 
"sheep.measuring.units", "sheep.susceptible", "sheep.cases", 
"sheep.deaths", "sheep.destroyed", "sheep.slaughtered", "cattle.measuring.units", 
"cattle.susceptible", "cattle.cases", "cattle.deaths", "cattle.destroyed", 
"cattle.slaughtered", "goat.measuring.units", "goat.susceptible", 
"goat.cases", "goat.deaths", "goat.destroyed", "goat.slaughtered", 
"remark", "code"), row.names = c(NA, 6L), class = "data.frame")

expect_is(agg_summaries(dat, var = "latitude", group = "code", mean), "data.frame")
})